server:
    port: 8083
spring:
    kafka:
        bootstrap-servers: pkc-7xoy1.eu-central-1.aws.confluent.cloud:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties:
            bootstrap:
                servers: pkc-7xoy1.eu-central-1.aws.confluent.cloud:9092
            sasl:
                jaas:
                    config: org.apache.kafka.common.security.plain.PlainLoginModule required username='VROSUZ57EQREH2KS' password='cPbRZ+qMcKi3vU5PmX/Nwu30TcCraQF6X4eLuTF0E9q+2tncbWp0+ZqeMfxGcXaz';
                mechanism: PLAIN
            security:
                protocol: SASL_SSL